# Generated by Django 5.1.4 on 2026-01-23 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('usuario_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('usuario_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_empresa.usuario_empresa')),
            ],
            options={
                'db_table': 'venta',
                'ordering': ['id_venta'],
            },
        ),
    ]
