# Generated by Django 5.1.4 on 2026-01-19 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivo', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='producto.producto'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['producto', 'orden'], name='archivo_product_30891a_idx'),
        ),
    ]
