# Generated by Django 5.1.4 on 2026-01-24 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('reservas', '0001_initial'),
        ('usuario_empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada'), ('completada', 'Completada')], default='pendiente', max_length=50)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario_empresa.usuario_empresa')),
            ],
            options={
                'db_table': 'reserva',
                'ordering': ['-fecha_reserva'],
                'unique_together': {('id_usuario', 'id_producto')},
            },
        ),
    ]
