# Generated by Django 5.1.4 on 2026-01-23 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido', models.BooleanField(default=False)),
                ('fecha_leido', models.DateTimeField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('id_notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notificaciones.notificacion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifica',
                'unique_together': {('id_usuario', 'id_notificacion')},
            },
        ),
    ]
