# Generated by Django 5.1.4 on 2026-01-19 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo', models.FileField(upload_to='productos/archivos/%Y/%m/%d/', verbose_name='Archivo')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'archivo',
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
    ]
