# Generated by Django 5.1.4 on 2026-01-23 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('archivo', models.FileField(upload_to='productos/archivos/%Y/%m/%d/', verbose_name='Archivo')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='producto.producto')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'db_table': 'archivo',
                'ordering': ['orden', 'fecha_creacion'],
                'indexes': [models.Index(fields=['producto', 'orden'], name='archivo_product_30891a_idx')],
            },
        ),
    ]
