# Generated by Django 5.1.4 on 2026-01-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('duracion_dias', models.IntegerField()),
                ('limite_productos', models.IntegerField()),
                ('limite_usuarios', models.IntegerField()),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'plan',
                'ordering': ['id_plan'],
            },
        ),
    ]
