# Generated by Django 5.1.4 on 2026-01-12 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente'), ('bloqueado', 'Bloqueado')], default='inactivo', max_length=50)),
                ('empresa_id', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('plan_id', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, to='planes.plan')),
            ],
            options={
                'db_table': 'suscripcion',
                'ordering': ['id_suscripcion'],
            },
        ),
    ]
