# Generated by Django 5.1.4 on 2026-01-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vencido', 'Vencido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=50)),
                ('comprobante_pago', models.FileField(blank=True, help_text='Comprobante de pago en formato PDF', null=True, upload_to='comprobantes/pagos/%Y/%m/%d/')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'suscripcion',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
