# Generated by Django 5.1.4 on 2026-01-15 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0002_initial'),
        ('planes', '0001_initial'),
        ('suscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='admin_aprobador',
            field=models.ForeignKey(blank=True, help_text='Admin que aprobó la suscripción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='empresa_id',
            field=models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='plan_id',
            field=models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, to='planes.plan'),
        ),
    ]
