# Generated by Django 5.1.4 on 2026-01-14 23:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Suscripción', 'verbose_name_plural': 'Suscripciones'},
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='admin_aprobador',
            field=models.ForeignKey(blank=True, help_text='Admin que aprobó la suscripción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suscripciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='comprobante_pago',
            field=models.FileField(blank=True, help_text='Comprobante de pago en formato PDF', null=True, upload_to='comprobantes/pagos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vencido', 'Vencido'), ('rechazado', 'Rechazado')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='suscripcion',
            name='fecha_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
