# Generated by Django 5.1.4 on 2026-01-12 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_Empresa',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('estado', models.CharField(choices=[('ACTIVO', 'activo'), ('INACTIVO', 'inactivo')], default='inactivo', max_length=50)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empresa_id', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
            options={
                'db_table': 'usuario_empresa',
                'ordering': ['id_usuario'],
            },
        ),
    ]
