# Generated by Django 5.1.4 on 2026-01-23 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('rubro', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente'), ('bloqueado', 'Bloqueado')], default='inactivo', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='admins.admin')),
            ],
            options={
                'db_table': 'empresa',
                'ordering': ['id_empresa'],
            },
        ),
    ]
