# Generated by Django 5.1.4 on 2026-01-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='empresa',
        ),
    ]
