# Generated by Django 5.1.4 on 2026-01-19 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='proveedor.proveedor'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre', 'empresa'], name='producto_nombre_4c68ee_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado', 'empresa'], name='producto_estado_123580_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria', 'empresa'], name='producto_categor_c197b7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('nombre', 'empresa')},
        ),
    ]
