# Generated by Django 5.1.4 on 2026-01-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('VENDEDOR', 'vendedor'), ('ADMIN', 'admin'), ('CLIENTE', 'cliente'), ('ADMIN_EMPRESA', 'admin_empresa')], default='cliente', max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACTIVO', 'activo'), ('INACTIVO', 'inactivo')], default='inactivo', max_length=50)),
            ],
            options={
                'db_table': 'Rol',
                'ordering': ['id_rol'],
            },
        ),
    ]
