# Generated by Django 5.1.4 on 2026-01-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('vendedor', 'Vendedor'), ('admin', 'Administrador'), ('cliente', 'Cliente'), ('admin_empresa', 'Administrador Empresa')], default='cliente', max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='inactivo', max_length=50)),
            ],
            options={
                'db_table': 'rol',
                'ordering': ['id_rol'],
            },
        ),
    ]
