# Generated by Django 5.1.4 on 2026-01-12 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rol',
            table='rol',
        ),
    ]
