# Generated by Django 5.1.4 on 2026-01-15 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('empresas', '0002_initial'),
        ('relacion_tiene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiene',
            name='id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AddField(
            model_name='tiene',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='tiene',
            unique_together={('id_cliente', 'id_empresa')},
        ),
    ]
