# Generated by Django 5.1.4 on 2026-01-23 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('nombre_admin', models.CharField(max_length=100)),
                ('telefono_admin', models.CharField(max_length=15)),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin',
                'ordering': ['nombre_admin'],
            },
        ),
    ]
