# Generated by Django 5.1.4 on 2026-01-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('warning', 'Advertencia'), ('success', 'Éxito'), ('error', 'Error'), ('stock', 'Stock Bajo'), ('venta', 'Nueva Venta'), ('compra', 'Nueva Compra'), ('reserva', 'Reserva')], default='info', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notificacion',
                'ordering': ['id_notificacion'],
            },
        ),
    ]
