# Generated by Django 5.1.4 on 2026-01-17 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('direccion_cliente', models.CharField(max_length=200)),
                ('telefono_cliente', models.CharField(max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ['nombre_cliente'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente_nit', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('ACTUALIZADO', 'Actualizado'), ('ELIMINADO', 'Eliminado')], max_length=20)),
                ('detalles', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó la acción')),
            ],
            options={
                'verbose_name': 'Auditoría de Cliente',
                'verbose_name_plural': 'Auditorías de Clientes',
                'db_table': 'auditoria_cliente',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['cliente_id', 'fecha'], name='auditoria_c_cliente_781561_idx'), models.Index(fields=['accion', 'fecha'], name='auditoria_c_accion_074996_idx'), models.Index(fields=['usuario', 'fecha'], name='auditoria_c_usuario_86d1c3_idx')],
            },
        ),
    ]
