# Generated by Django 5.1.4 on 2026-01-17 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditoriacliente',
            name='auditoria_c_cliente_781561_idx',
        ),
        migrations.RemoveField(
            model_name='auditoriacliente',
            name='cliente',
        ),
        migrations.AddField(
            model_name='auditoriacliente',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='auditoriacliente',
            name='cliente_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='auditoriacliente',
            index=models.Index(fields=['cliente_id', 'fecha'], name='auditoria_c_cliente_781561_idx'),
        ),
    ]
