# Generated by Django 5.1.4 on 2026-01-12 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0002_alter_rol_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=256)),
                ('estado', models.CharField(choices=[('ACTIVO', 'activo'), ('INACTIVO', 'inactivo')], default='inactivo', max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('rol_id', models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.CASCADE, to='roles.rol')),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['id_usuario'],
            },
        ),
    ]
