# Generated by Django 5.1.4 on 2026-01-12 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(db_column='rol', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='roles.rol'),
        ),
    ]
